name: koperasi_undiksha
description: Aplikasi perbankan untuk Koperasi Undiksha.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  crypto: ^3.0.3
  flutter_local_notifications: ^14.1.1
  flutter_secure_storage: ^8.0.0
  intl: ^0.18.1
  shared_preferences: ^2.1.1
  timezone: ^0.9.2
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
